---
- debug: var=env
- debug: var=app
- debug: var=service
- local_action:
    module: ec2_elb_facts
    names:
    - "{{ env }}-{{ app }}-{{ service }}-green"
  register: elb_green

- local_action:
    module: ec2_elb_facts
    names:
    - "{{ env }}-{{ app }}-{{ service }}-blue"
  register: elb_blue

- local_action:
    module: ec2_asg_facts
    name: "{{ env }}-{{ app }}-{{ service }}-green"
  register: asg_green

- local_action:
    module: ec2_asg_facts
    name: "{{ env }}-{{ app }}-{{ service }}-blue"
  register: asg_blue

- name: "elb"
  local_action:
    module: debug
    msg: "{{ item }}"
  with_items: "{{ elb_green.elbs, elb_blue.elbs }}"

- name: "asg"
  local_action:
    module: debug
    msg: "{{ item }}"
  with_items: "{{ asg_green.results, asg_blue.results }}"

- name: "building lists of instances"
  set_fact:
    instances_green: "{{ asg_green.results[0].instances }}"
    instances_blue: "{{ asg_blue.results[0].instances }}"

- name: "building lists of instance_ids"
  set_fact:
    instance_ids_green: "{{ (instances_green | map(attribute='instance_id')) | list }}"
    instance_ids_blue: "{{ (instances_blue | map(attribute='instance_id')) | list }}"

- name: "green elb"
  local_action:
    module: debug
    msg: "{{ elb_green }}"

- name: "green instances"
  local_action:
    module: debug
    msg: "{{ instances_green }}"

- name: "green instance ids"
  local_action:
    module: debug
    msg: "{{ instance_ids_green }}"

- name: "blue elb"
  local_action:
    module: debug
    msg: "{{ elb_blue }}"

- name: "blue instances"
  local_action:
    module: debug
    msg: "{{ instances_blue}}"

- name: "blue instance ids"
  local_action:
    module: debug
    msg: "{{ instance_ids_blue }}"

- name: "green instance ids"
  local_action:
    module: debug
    msg: "{{ instance_ids_green }}"

- name: "promoting green to blue"
  local_action:
    module: shell
    args: "script/promote {{ env }}-{{ app }}-{{ service }}-blue {{ instance_ids_green | join(' ') }}"
  register: green_promotion

- name: "green promoted"
  local_action:
    module: debug
    msg: "{{ green_promotion }}"

- name: "taking the old blues out"
  local_action:
    module: shell
    args: "script/demote {{ instance_ids_blue | join(' ') }}"
  register: blue_demoted

- name: "blue demoted"
  local_action:
    module: debug
    msg: "{{ blue_demoted }}"

